# syntax=docker/dockerfile:1
FROM golang:1.24

# Install Java (OpenJDK)
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy go mod and sum files
COPY go.mod ./

# Download dependencies
RUN go mod download

# Copy the source
COPY . .

# Build the Go binary
RUN go build -o executor .

# Expose port
EXPOSE 8080

# Run the binary
CMD ["go", "run", "main.go"]
